export default {
    HOME: "/",
    ALLPETS: "/all-pets",
    ALLBREEDS: "/all-breeds",
    PETSDETAIL: "/pets-detail/:id",
    ADOPTIONFORM: "/adoption-form",
    CHECKOUT: "/checkout",
    PETSHOP: "/shop",
    PRODUCTDETAIL: "/product/:id",
    SEARCHPAGE: "/search-page",
    ABOUTME: "/about-me",
    SHOPPINGCART: "/cart",
    CATEGORYPET: "/category-pet",
    PETBYBREED: "/all-breeds/category/:category/:breed",
    BREEDBYCATEGORY: "/all-breeds/category/:category",
    HISTORYPURCHASE: "/history-purchase",
};
