export default {
    HOME: "/",
    ALLPETS: "/all-pets",
    ALLBREEDS: "/all-breeds",
    PETSDETAIL: "/pets-detail/:id",
    ADOPTIONFORM: "/adoption-form",
    STATUSREQUEST: "/adoption-request",
    ADOPTEDHISTORY: "/adopted-history",
    CHECKOUT: "/checkout",
    PETSHOP: "/shop",
    PRODUCTDETAIL: "/product/:id",
    SEARCHPAGE: "/search-page",
    ABOUTME: '/about-me',
    SHOPPINGCART: "/cart",
    CATEGORYPET: "/category-pet",
    BREEDBYCATEGORY: "/all-breeds/category/:category",
};
